FROM rust:1.71.1 AS builder

WORKDIR /app
RUN apt update && apt install lld clang -y
COPY . .
ENV SQLX_OFFLINE true
RUN cargo build --release

FROM debian:bookworm-slim AS runtime

WORKDIR /app

COPY --from=builder /app/target/release/home home
COPY configuration configuration
ENV APP_ENVIRONMENT production
ENTRYPOINT [ "./target/release/home" ]